{
 "title": "Various",
 "description": "Various panels",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "op-node - Inflight events by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "op_node_default_events_enqueued",
     "legendFormat": "{{event_type}} ; {{namespace}}"
    }
   ]
  },
  {
   "title": "op-supervisor - Inflight events by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "op_supervisor_default_events_enqueued",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "op-node - Total inflight events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "op_node_default_events_total_enqueued",
     "legendFormat": "total ; {{namespace}}"
    }
   ]
  },
  {
   "title": "op-supervisor - Total inflight events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "op_supervisor_default_events_total_enqueued",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "op-node - Count of emitted events by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(op_node_default_events_processed[60s])",
     "legendFormat": "{{deriver}} ; {{event_type}} ; {{instance}}"
    }
   ]
  }
 ]
}